# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5bc0f5bc5793b78d3f0729e6340630eb5c45864e2867a1a654e0148f945dcd893750bbd1b2b1d6f82c636b176d8971585397530022b7bc15a9f12f67796461c3

test:
  secret_key_base: c114d685dffcec13dc018dc9ddba01e509c4410c7541347e27edbaa5185c6128103ed8ee98e0bbc6f873fbaf8174e72d816a7a4d72f9a1d12da7572177e23bce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
